// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzvrquzwwhrpxkvkukgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6dnJxdXp3d2hycHhrdmt1a2dkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MDQyNTEsImV4cCI6MjA2OTA4MDI1MX0.zlybPz7P1DDtWDriFrWfmBlIO59jRXzZ3D4e_txQ2bg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});